#define SERIAL_BAUD_RATE 115200

#define STATE_LENGTHS {7000 ,2000, 4000}

#define NUM_OF_MODES 5

#define ENCODER_CLK 2
#define ENCODER_DT 3
#define ENCODER_BTN 4

#define MODE_BTN 4
#define DEBOUNCE_PERIOD 50


#define DUTY_CYCLE_LCD_PERCENT_DEFAULT 100
#define STEALTHMODE_DEFAULT false
#define VOLUME_DEFAULT 0
#define VOLUME_CONTROL_EXPONENT_COEFFICIENT 0.25
