#define VERSION "v1.0"
#define PROJECT_TITLE "Aion"
#define AUTHOR_NICKNAME "NotSirius-A"
#define SHORT_GITHUB_LINK "github.com/NotSirius-A"
#define GITHUB_LINK "https://github.com/NotSirius-A"
#define DATE_CREATED "09/04/2022"
#define DATE_UPDATED "09/04/2022"




#define SERIAL_BAUD_RATE 115200


/*
  A0 - 14  
  A1 - 15
  A2 - 16
  A3 - 17
  A4 - 18
  A5 - 19
*/

#define ENCODER_CLK 2
#define ENCODER_DT 3
#define ENCODER_BUTTON 4
#define ENCODER_VCC 5 
#define SPEAKER_PIN 6 //PWM
#define PRIMARY_BUTTON 17
#define SECONDARY_BUTTON ENCODER_BUTTON
#define LCD_TFT_CLK 13
#define LCD_TFT_DIN 13
#define LCD_TFT_CS 10
#define LCD_TFT_RST 9 
#define LCD_TFT_DC 8
#define LCD_BACKLIGHT 7
#define RED_LED_PIN 14
#define BLUE_LED_PIN 15
#define GREEN_LED_PIN 16

#define SPLASH_SCREEN_STR1 PROJECT_TITLE
#define SPLASH_SCREEN_STR2 SHORT_GITHUB_LINK
#define SPLASH_SCREEN_DURATION 2000

#define MODE_BUTTON PRIMARY_BUTTON
#define NUM_OF_MODES 7

#define DEBOUNCE_PERIOD 50

#define VOLUME_CONTROL_EXPONENT_COEFFICIENT 0.25

#define DUTY_CYCLE_CHANGE_MULTIPLIER 5

#define START_MODE_DEFAULT 0
#define DUTY_CYCLE_LCD_PERCENT_DEFAULT 100
#define STEALTHMODE_DEFAULT false
#define VOLUME_DEFAULT 5
